name: Setup and Build Package

on:
  workflow_call:
    inputs:
      LANGUAGE:
        description: "Programming Language to Package"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up environment based on LANGUAGE
        id: setup_language
        run: |
          echo "LANGUAGE=${{ inputs.LANGUAGE }}"
          echo "Setting up environment for ${{ inputs.LANGUAGE }}"

          if [[ "${{ inputs.LANGUAGE }}" == "dotnet" ]]; then
            echo "Setting up .NET"
            sudo apt-get install -y dotnet-sdk-8.0
          elif [[ "${{ inputs.LANGUAGE }}" == "java" ]]; then
            echo "Setting up Java"
            sudo apt-get install -y openjdk-11-jdk maven
          elif [[ "${{ inputs.LANGUAGE }}" == "python" ]]; then
            echo "Setting up Python"
            sudo apt-get install -y python3-pip
          elif [[ "${{ inputs.LANGUAGE }}" == "kotlin" ]]; then
            echo "Setting up Kotlin"
            sudo apt-get install -y openjdk-11-jdk
            curl -s https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install kotlin
          elif [[ "${{ inputs.LANGUAGE }}" == "react" || "${{ inputs.LANGUAGE }}" == "javascript" ]]; then
            echo "Setting up Node.js"
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
          else
            echo "Language not supported!"
            exit 1
          fi

      - name: Set package name and version
        id: set_package
        run: |
          PACKAGE_ID="example-package"
          PACKAGE_VERSION="1.0.${{ github.run_id }}"
          echo "PACKAGE_ID=${PACKAGE_ID}" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV

      - name: Update POM file with package details (for Java)
        if: inputs.LANGUAGE == 'java'
        run: |
          sed -i "s|\${PACKAGE_ID}|${{ env.PACKAGE_ID }}|g" pom.xml
          sed -i "s|\${PACKAGE_VERSION}|${{ env.PACKAGE_VERSION }}|g" pom.xml
          echo "Updated POM file with PACKAGE_ID=${{ env.PACKAGE_ID }} and PACKAGE_VERSION=${{ env.PACKAGE_VERSION }}"

      - name: Restore dependencies (if applicable)
        run: |
          if [[ "${{ inputs.LANGUAGE }}" == "dotnet" ]]; then
            dotnet restore
          elif [[ "${{ inputs.LANGUAGE }}" == "java" ]]; then
            mvn clean install
          elif [[ "${{ inputs.LANGUAGE }}" == "python" ]]; then
            pip install -r requirements.txt
          elif [[ "${{ inputs.LANGUAGE }}" == "kotlin" ]]; then
            gradle build
          elif [[ "${{ inputs.LANGUAGE }}" == "react" || "${{ inputs.LANGUAGE }}" == "javascript" ]]; then
            npm install
          fi

      - name: Build project
        run: |
          if [[ "${{ inputs.LANGUAGE }}" == "dotnet" ]]; then
            dotnet build --configuration Release
          elif [[ "${{ inputs.LANGUAGE }}" == "java" ]]; then
            mvn clean package
          elif [[ "${{ inputs.LANGUAGE }}" == "python" ]]; then
            python setup.py install
          elif [[ "${{ inputs.LANGUAGE }}" == "kotlin" ]]; then
            gradle build
          elif [[ "${{ inputs.LANGUAGE }}" == "react" || "${{ inputs.LANGUAGE }}" == "javascript" ]]; then
            npm run build
          fi
