name: Setup and Build Package

on:
  workflow_call:
    inputs:
      LANGUAGE:
        description: "Programming Language to Package"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up environment based on LANGUAGE
        id: setup_language
        run: |
          echo "LANGUAGE=${{ inputs.LANGUAGE }}"
          echo "Setting up environment for ${{ inputs.LANGUAGE }}"

          if [[ "${{ inputs.LANGUAGE }}" == "dotnet" ]]; then
            echo "Setting up .NET"
            sudo apt-get install -y dotnet-sdk-8.0
          elif [[ "${{ inputs.LANGUAGE }}" == "java" ]]; then
            echo "Setting up Java"
            sudo apt-get install -y openjdk-11-jdk 
          elif [[ "${{ inputs.LANGUAGE }}" == "python" ]]; then
            echo "Setting up Python" 
            sudo apt-get install -y python3-pip
          elif [[ "${{ inputs.LANGUAGE }}" == "kotlin" ]]; then
            echo "Setting up Kotlin"
            sudo apt-get install -y openjdk-11-jdk
            curl -s https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install kotlin
          elif [[ "${{ inputs.LANGUAGE }}" == "react" || "${{ inputs.LANGUAGE }}" == "javascript" ]]; then
            echo "Setting up Node.js"
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
          else
            echo "Language not supported!"
            exit 1
          fi

      - name: Build project
        run: |
          if [[ "${{ inputs.LANGUAGE }}" == "dotnet" ]]; then
            dotnet build --configuration Release
          elif [[ "${{ inputs.LANGUAGE }}" == "java" ]]; then
             mvn clean package \
              -Dpackage.id=${{ env.PACKAGE_ID }} \
              -Dpackage.version=${{ env.PACKAGE_VERSION }}
          elif [[ "${{ inputs.LANGUAGE }}" == "python" ]]; then
            python setup.py install
          elif [[ "${{ inputs.LANGUAGE }}" == "kotlin" ]]; then
            gradle build
          elif [[ "${{ inputs.LANGUAGE }}" == "react" || "${{ inputs.LANGUAGE }}" == "javascript" ]]; then
            npm run build
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./build/  
